// <auto-generated />
namespace CrmAPP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Bericht_FK_Attrs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bericht_FK_Attrs));
        
        string IMigrationMetadata.Id
        {
            get { return "202511051553309_Bericht_FK_Attrs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
