// <auto-generated />
namespace CrmAPP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class PersonalProjekte_KundenDatenID_Ekleme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonalProjekte_KundenDatenID_Ekleme));
        
        string IMigrationMetadata.Id
        {
            get { return "202511051454341_PersonalProjekte_KundenDatenID_Ekleme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
